name: Sincronizar 

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Descargar el artefacto de la última corrida
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: 'Sincronizar'
          branch: main
          path: .
          name: sqlite-database-*

      - name: Configuracion de python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
          cache: 'pip'
          
      - name: Instalar las dependencias
        run: | 
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall -r requirements.txt

      - name: Ejecutar script de sincronizacion
        env:
          CONNECTEAM_API_KEY: ${{ secrets.CONNECTEAM_API_KEY }}
          ODOO_API_KEY: ${{ secrets.ODOO_API_KEY }}
          URL_Odoo: ${{ secrets.URL_Odoo }}
          DB_Odoo: ${{ secrets.DB_Odoo }}
          USER_Odoo: ${{ secrets.USER_Odoo }}
          MS_TENANT: ${{ secrets.MS_TENANT }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          
        run:  python app_registro_git.py

      - name: Subir DB como artefacto (backup histórico)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-database-${{ github.run_number }}
          path: ./form_entries.db
        


        
