name: Sincronizar 

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout del c√≥digo
        uses: actions/checkout@v4

      - name: Configuracion de python 3.11.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Descargar base de datos SQLite
        uses: actions/download-artifact@v4
        with:
          name: sqlite-database
          path: .
          
      - name: Instalar las dependencias
        run: | 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script de sincronizacion
        env:
          CONNECTEAM_API_KEY: ${{ secrets.CONNECTEAM_API_KEY }}
          ODOO_API_KEY: ${{ secrets.ODOO_API_KEY }}
          URL_Odoo: ${{ secrets.URL_Odoo }}
          DB_Odoo: ${{ secrets.DB_Odoo }}
          USER_Odoo: ${{ secrets.USER_Odoo }}
          MS_TENANT: ${{ secrets.MS_TENANT }}
          MS_CLIENT_ID: ${{ secrets.MS_CLIENT_ID }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          
        run: ./app_registro_git.py

      - name: Subir base de datos de SQLite
        uses: actions/upload-artifact@v4
        with: 
          name: sqlite-database
          path: ./form_entries.db
        

        
